version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
  - source: /SRClogo-remover.png
    destination: /var/www/html
    overwrite: yes
hooks:
  BeforeInstall:
    - location: /install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: /deploy.sh
      timeout: 300
      runas: root
